language: node_js
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '8'

branches:
  except:
    - publish

script:
  - ( yarn prettify:check || yarn lint || true ) && yarn test:prod && yarn build

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip-cleanup: true
    on: 
      branch: master
